# About exemptions

**Exemptions** are a way for researchers to request and obtain exemptions from SecureDNA screening.

A researcher who needs to synthesize sequences of concern can create
an **exemption token request** (a short file, generated by SecureDNA's
tools) and send it to their organization's biosafety authority
(BSA). This request specifies which organisms or sequences are
necessary for their work.

The BSA approves this request, and sends back an **exemption token**. This token automatically allows further orders when submitted alongside a SecureDNA screening request. It is reuseable for any number of orders and across multiple participating vendors.

To get started, follow one of the guides below.

<!-- * For **everyone**: [[Exemption system overview]] describes the basic concept and essential terminology -->
* For **researchers**: [Requesting exemptions](../requesting-exemptions/index.qmd) describes how to request a token from a biosafety authority
* For **biosafety authorities**: [Approving exemptions](../approving-exemptions/index.qmd) describes how tokens may be granted

For an in-depth overview, see [Advanced overview](../exemptions-advanced/index.qmd).

<!-- ## Screenshots

These [[screenshots|All-flow-screenshots]] demonstrate typical interactions for:
* researchers/customers who are [[requesting an exemption token to allow synthesis|Researcher-flow-screenshots]]
* biosafety authorities who are [[approving an exemption request|BSA-flow-screenshots]]. -->
