[package]
name = "shared_types"
version = { workspace = true }
publish = { workspace = true }
license = { workspace = true }
edition = "2024"

[dependencies]
base64 = "0.22.0"
http = { version = "1.0.0", optional = true }
prometheus = "0.14.0"
regex = "1.11.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
serde_plain = "1.0.1"
thiserror = "2.0.3"
uuid = {version = "1.23.1", features = ["v4", "js"]}

certificates = { path = "../certificates" }
doprf = {path = "../doprf"}
pipeline_bridge = { path = "../pipeline_bridge" }

[dev-dependencies]
quickcheck = "1.0"
