[package]
name = "certificate_tests"
edition = "2021"
license.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
certificates = { path = "../certificates" }

[dev-dependencies]
once_cell = "1.19.0"
paste = "1.0.14"
