[workspace]
members = [
    "crates/*",
    "crates/wasm_bindings/certificates",
    "crates/wasm_bindings/quickdna",
    "crates/wasm_bindings/screening",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
version = "1.1.0"
publish = false

[workspace.dependencies]
again = { git = "https://github.com/SecureDNA/again", rev = "a8a560bd2e986be6b5873a8fcc89f802e2441f4d" }
curve25519-dalek = "4.1.3"
http = "1.1.0"
http-body-util = "0.1.0"
hyper = "1.6.0"
quickdna = { git = "https://github.com/SecureDNA/quickdna", tag = "v0.6.0", default-features = false }
rasn = "0.10.0"
serde = "1.0"
tempfile = "3.19.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[profile.release-with-debug]
inherits = "release"
debug = true
overflow-checks = true
