version: '3'

# SecureDNA env vars are picked up through `.env` in the repo root.

x-environment: &keyserver-common-env
    {}
    #"RUST_LOG": "info"

services:
  client:
    image: ghcr.io/securedna/client:${SECUREDNA_TAG}
    ports:
      - "80:80"
    depends_on:
      - keyserver1
      - keyserver2
      - keyserver3
    command: [
      "./synthclient",
    ]
    volumes:
      - "${TEST_CERTS_PATH:-./test/certs}:/certs/"
      - "${TEST_CFG_PATH:-./test/cfg}:/cfg/"
    environment:
      "SECUREDNA_CFG_PATH": "/cfg/synthesizer.toml"
  hdbserver:
    image: ghcr.io/securedna/hdbserver:${SECUREDNA_TAG}
    ports:
      - "5300:5300"
    volumes:
      - "${TEST_HDB_PATH:-./data/hdb}:/data/hdb"
      - "${TEST_CERTS_PATH:-./test/certs}:/certs/"
      - "${TEST_CFG_PATH:-./test/cfg}:/cfg/"
    environment:
      "SECUREDNA_CFG_PATH": "/cfg/database.toml"
  keyserver1:
    image: ghcr.io/securedna/keyserver:${SECUREDNA_TAG}
    ports:
      - "5301:5301"
    volumes:
      - "${TEST_CERTS_PATH:-./test/certs}:/certs/"
      - "${TEST_CFG_PATH:-./test/cfg}:/cfg/"
    environment:
      <<: *keyserver-common-env
      "SECUREDNA_CFG_PATH": "/cfg/03.keyserver-01.toml"
  keyserver2:
    image: ghcr.io/securedna/keyserver:${SECUREDNA_TAG}
    ports:
      - "5302:5302"
    volumes:
      - "${TEST_CERTS_PATH:-./test/certs}:/certs/"
      - "${TEST_CFG_PATH:-./test/cfg}:/cfg/"
    environment:
      <<: *keyserver-common-env
      "SECUREDNA_CFG_PATH": "/cfg/03.keyserver-02.toml"
  keyserver3:
    image: ghcr.io/securedna/keyserver:${SECUREDNA_TAG}
    ports:
      - "5303:5303"
    volumes:
      - "${TEST_CERTS_PATH:-./test/certs}:/certs/"
      - "${TEST_CFG_PATH:-./test/cfg}:/cfg/"
    environment:
      <<: *keyserver-common-env
      "SECUREDNA_CFG_PATH": "/cfg/03.keyserver-03.toml"
