[toolchain]
# The default profile includes rustc, rust-std, cargo, rust-docs, rustfmt and clippy.
# https://rust-lang.github.io/rustup/concepts/profiles.html
profile = "default"

# for rust-analyzer
components = ["rust-src"]

# When changing, also change the default image in the Earthfile
channel = "1.79.0"

# Host platform included by default, this list is additive
targets = [ "wasm32-unknown-unknown" ]
