[package]
name = "scurl"
edition = "2021"
license.workspace = true
version.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.3", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
tracing.workspace = true
tracing-subscriber = "0.3.18"
hex = "0.4.3"
serde.workspace = true
serde_json = "1.0.114"

hdb_api = { path = "../hdb_api" }
http_client = { path = "../http_client" }
shared_types = { path = "../shared_types" }
scep_client_helpers = { path = "../scep_client_helpers" }
securedna_versioning = { path = "../securedna_versioning" }
certificates = { path = "../certificates" }
doprf = { path = "../doprf" }
scep = { path = "../scep" }
packed_ristretto = { path = "../packed_ristretto" }
doprf_client = { path = "../doprf_client" }
