[package]
name = "certificate-client"
version = { workspace = true }
publish = { workspace = true }
license = { workspace = true }
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.60", features = ["derive", "cargo"] }
dirs = "6.0.0"
rasn = { workspace = true }
rpassword = "7.4.0"
serde = "1.0.188"
thiserror = "2.0.3"
time = "0.3.47"
certificates = { path = "../certificates" }
doprf = { path = "../doprf" }
serde_json = "1.0.94"
hex = "0.4.3"

[dev-dependencies]
anyhow = "1.0.75"
assert_cmd = "2.2.0"
tempfile = { workspace = true }
temp-env = "0.3.6"

[target.'cfg(unix)'.dev-dependencies]
faketime = "0.2.1"
rexpect = "0.7.0"

[features]
env_passphrase = []
cert_tests = []

[[bin]]
name = "sdna-audit"
path = "src/bin/audit.rs"

[[bin]]
name = "sdna-create-key"
path = "src/bin/create_key.rs"

[[bin]]
name = "sdna-create-cert"
path = "src/bin/create_cert.rs"

[[bin]]
name = "sdna-inspect-cert"
path = "src/bin/inspect_cert.rs"

[[bin]]
name = "sdna-sign-cert"
path = "src/bin/sign_cert.rs"

[[bin]]
name = "sdna-retrieve-cert-request"
path = "src/bin/retrieve_cert_request.rs"

[[bin]]
name = "sdna-merge-cert"
path = "src/bin/merge_cert.rs"

[[bin]]
name = "sdna-create-token"
path = "src/bin/create_token.rs"

[[bin]]
name = "sdna-inspect-token"
path = "src/bin/inspect_token.rs"

[[bin]]
name = "sdna-sign-token"
path = "src/bin/sign_token.rs"
