// Copyright 2021-2026 SecureDNA Stiftung (SecureDNA Foundation) <licensing@securedna.org>
// SPDX-License-Identifier: MIT OR Apache-2.0

use std::fmt;
use std::sync::Arc;

use curve25519_dalek::ristretto::RistrettoPoint;
use itertools::Itertools;
use rand::{CryptoRng, RngCore};
use sha3::Sha3_512;

use crate::active_security::ActiveSecurityKey;
use crate::party::KeyserverId;
use crate::prf::{CompressedCompletedHashValue, CompressedHashPart, CompressedQuery};
use crate::{Blinder, Verifier};

use crate::prf::DecodeError;

#[derive(Debug, Clone)]
pub enum QueryError {
    WrongSizeResponse,
    MissingKeyserverResponse,
    InvalidRistrettoPoint(DecodeError),
    ValidationFailed(Vec<KeyserverId>),
}

impl std::error::Error for QueryError {}

impl fmt::Display for QueryError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            QueryError::WrongSizeResponse => {
                write!(f, "Query response has the wrong size")
            }
            QueryError::InvalidRistrettoPoint(err) => {
                write!(
                    f,
                    "Invalid ristretto point returned from keyservers: {err:?}"
                )
            }
            QueryError::ValidationFailed(keyservers) => {
                write!(
                    f,
                    "Query response did not validate. Responsible keyservers: {:?}",
                    keyservers
                )
            }
            QueryError::MissingKeyserverResponse => {
                write!(f, "Missing keyserver response")
            }
        }
    }
}

/// Holds information necessary to reconstitute keyserver responses into completed hashes.
#[derive(Clone)]
pub struct QueriesSecurityContext {
    num_windows: usize,
    verifier: Verifier,
    blinder: Blinder,
}

/// Builds [`CompressedQuery`]s from windows.
///
/// Given an iterator of windows, this function hashes and blinds the windows, converting them
/// into an `Arc<[CompressedQuery]>`, which is returned along with a [`QueriesSecurityContext`].
/// The [`QueriesSecurityContext`] may be used to recombine keyserver responses into
/// [`Vec<CompressedCompletedHashValue>`]s.
///
/// `padding` is the number of random windows to add to the returned `Arc<[CompressedQuery]>`.
/// Padding should be used to increase the total number of windows to at least 100 or so,
/// in order to avoid timing attacks related to hash verification. (see [`Verifier`] for details)
///
/// `security_strength` controls how strong verification is; it's just passed to [`Verifier`].
pub fn setup_queries<WI>(
    mut rng: impl CryptoRng + RngCore,
    windows: WI,
    padding: usize,
    security_strength: u8,
) -> (Arc<[CompressedQuery]>, QueriesSecurityContext)
where
    WI: IntoIterator<Item: AsRef<[u8]>>,
{
    let windows = windows.into_iter();
    // If these are smaller than the actual iter... oh well, we'll reallocate
    // If they're too big... that's really a programming error; we'll let Vec deal with that
    let (min_windows, max_windows) = windows.size_hint();
    let num_windows = max_windows.unwrap_or(min_windows);
    let num_rps = num_windows.saturating_add(padding).saturating_add(1);
    let mut rps = Vec::with_capacity(num_rps);
    rps.extend(windows.map(|w| RistrettoPoint::hash_from_bytes::<Sha3_512>(w.as_ref())));
    rps.extend((0..padding).map(|_| RistrettoPoint::random(&mut rng)));

    let (balancer, verifier) = Verifier::balancer_and_verifier(&mut rng, security_strength, &rps);
    rps.push(balancer);
    let blinder = Blinder::from_blinding_in_place(&mut rng, &mut rps);

    let queries = rps.into_iter().map(CompressedQuery::from_rp).collect();
    let security_context = QueriesSecurityContext {
        num_windows,
        verifier,
        blinder,
    };
    (queries, security_context)
}

impl QueriesSecurityContext {
    /// Recombines keyserver responses into [`Vec<CompressedCompletedHashValue>`].
    ///
    /// The query responses must be [`Vec<CompressedCompletedHashValue>`]s generated by scaling
    /// [`setup_queries`]'s `Arc<[CompressedQuery]>` by a value compatible with the given
    /// [`ActiveSecurityKey`].
    ///
    /// If the number of responses differs from the [`ActiveSecurityKey`]'s quorum size, this
    /// will return [`QueryError::MissingKeyserverResponse`]. Note that this also occurs if there
    /// are too many responses.
    ///
    /// If any response contains the wrong number of [`CompressedHashPart`]s, this will return
    /// [`QueryError::WrongSizeResponse`].
    ///
    /// If any [`CompressedHashPart`] cannot be decompressed into valid ristretto point,
    /// this will return [`QueryError::InvalidRistrettoPoint`].
    ///
    /// If the responses don't match the provided [`ActiveSecurityKey`], this will return
    /// [`QueryError::ValidationFailed`].
    pub fn recombine(
        self,
        responses: &[(KeyserverId, Vec<CompressedHashPart>)],
        active_security_key: &ActiveSecurityKey,
    ) -> Result<Vec<CompressedCompletedHashValue>, QueryError> {
        if responses.len() != active_security_key.supported_quorum() {
            return Err(QueryError::MissingKeyserverResponse);
        }
        let expected_len = self.verifier.expected_elements();
        if responses.iter().any(|(_, hp)| hp.len() != expected_len) {
            return Err(QueryError::WrongSizeResponse);
        }
        let keyservers = responses.iter().map(|(ks_id, _)| *ks_id).collect();

        let Self {
            num_windows,
            verifier,
            blinder,
        } = self;
        let blinded_hashes = combined_hashes(responses);
        let rps: Result<Vec<_>, _> = blinder.try_unblinded(blinded_hashes).collect();
        let rps = rps.map_err(QueryError::InvalidRistrettoPoint)?;

        let db_key_commitment = active_security_key.database_key_commitment();
        if verifier.verify(&rps, db_key_commitment).is_err() {
            let bad_keyservers = responses
                .iter()
                .filter_map(|(keyserver, hash_parts)| {
                    let blinded = hash_parts
                        .iter()
                        // NOTE: unwrap won't panic because otherwise `rps?` would have bailed.
                        // Also, can't flatmap because size-hint mismatch angers multiscalar mul.
                        .map(|hash_part| hash_part.to_rp().unwrap());
                    let rps = blinder.unblinded(blinded);
                    let ks_commitment =
                        active_security_key.adjusted_keyserver_commitment(*keyserver, &keyservers);
                    verifier
                        .verify(rps, &ks_commitment)
                        .is_err()
                        .then_some(*keyserver)
                })
                .sorted() // TODO: Should ValidationFailed hold a KeyserverIdSet?
                .collect();
            return Err(QueryError::ValidationFailed(bad_keyservers));
        }

        let completed_hashes = rps
            .into_iter()
            .map(CompressedCompletedHashValue::from_rp)
            .take(num_windows)
            .collect();
        Ok(completed_hashes)
    }
}

// For each query, decompresses and sums its hashparts.
// Note: although we're not actually using the `KeyserverId`s right now, I'm still taking them
// in case we later want to return better diagnostics about which keyserver and hash was invalid.
fn combined_hashes(
    responses: &[(KeyserverId, Vec<CompressedHashPart>)],
) -> impl Iterator<Item = Result<RistrettoPoint, DecodeError>> + use<'_> {
    let mut hashpart_iters: Vec<_> = responses
        .iter()
        .map(|(_ks_id, hash_parts)| hash_parts.iter().map(CompressedHashPart::to_rp))
        .collect();
    // TODO: find way to make proper size hint for better efficiency?
    std::iter::from_fn(move || hashpart_iters.iter_mut().map(Iterator::next).sum())
}

#[cfg(test)]
mod tests {
    use super::*;

    use curve25519_dalek::scalar::Scalar;
    use quickcheck::{Arbitrary, Gen, TestResult, quickcheck};
    use rand::Rng;
    use rand::rngs::OsRng;
    use rand::seq::SliceRandom;

    use crate::party::KeyserverIdSet;
    use crate::prf::{HashPart, KeyShare, Query, SECURITY_PARAMETER};
    use crate::testutil::{KeyShares, TestRng};

    // TODO: Wish I knew a good way to test security_strength... Right now, if that were broken,
    // no tests would catch it. :(

    #[derive(Clone, Debug)]
    struct Dna(String);

    impl Arbitrary for Dna {
        fn arbitrary(g: &mut Gen) -> Self {
            // Using Vec::arbitrary(g) until g.gen_range(0..g.size()) is public
            let len = 3 * Vec::<()>::arbitrary(g).len();
            let dna = (0..len)
                .filter_map(|_| g.choose(&['a', 'c', 'g', 't']))
                .collect();
            Self(dna)
        }
    }

    fn random_populated_subset(
        rng: &mut (impl RngCore + CryptoRng),
        keyservers: &KeyserverIdSet,
    ) -> KeyserverIdSet {
        let subset_size = rng.gen_range(1..keyservers.len());
        let keyserver_ids = Vec::from(keyservers.clone());
        keyserver_ids
            .choose_multiple(rng, subset_size)
            .cloned()
            .collect()
    }

    fn hash_via_keyshares(
        rng: impl CryptoRng + RngCore,
        keyshares: &KeyShares,
        quorum_set: &KeyserverIdSet,
        padding: usize,
        windows: impl IntoIterator<Item: AsRef<[u8]>>,
    ) -> Result<Vec<CompressedCompletedHashValue>, QueryError> {
        let (queries, security_context) = setup_queries(rng, windows, padding, SECURITY_PARAMETER);
        let responses = keyshares.apply_keyshares(quorum_set, queries.iter().copied());
        security_context.recombine(&responses, &keyshares.active_security_key)
    }

    fn hash_via_key(
        key: &KeyShare,
        windows: impl IntoIterator<Item: AsRef<[u8]>>,
    ) -> Vec<CompressedCompletedHashValue> {
        windows
            .into_iter()
            .map(|window| {
                let rp = RistrettoPoint::hash_from_bytes::<Sha3_512>(window.as_ref());
                key.apply(Query::from_rp(rp)).compress().as_bytes().into()
            })
            .collect()
    }

    fn corrupt_hashpart(hash_part: &mut CompressedHashPart) {
        let mut bytes = *hash_part.as_bytes();
        bytes[0] = 0xff;
        *hash_part = CompressedHashPart::from(bytes);
    }

    // Quick sanity check... Run with -- --ignored to do more comprehensive tests
    #[test]
    fn distributed_keyshare_application_matches_single_key_application() {
        let mut rng = OsRng;

        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let keyshares = KeyShares::random(&mut rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(&mut rng);
        let windows = [
            "foobar",
            "The five boxing wizards jump quickly.",
            "",
            "acgtacgtacgt",
            "xyzzy",
        ];
        let padding = 0;

        assert_eq!(
            hash_via_keyshares(rng, &keyshares, &quorum_set, padding, windows).unwrap(),
            hash_via_key(&keyshares.secret, windows),
        );
    }

    #[test]
    fn padding_does_not_affect_output_length() {
        let mut rng = OsRng;

        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let keyshares = KeyShares::random(&mut rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(&mut rng);

        let windows = [
            "foobar",
            "The five boxing wizards jump quickly.",
            "",
            "acgtacgtacgt",
            "xyzzy",
        ];

        for padding in [0, 1, 2, 3, 8, 25] {
            let (queries, security_context) =
                setup_queries(rng, windows, padding, SECURITY_PARAMETER);
            let responses = keyshares.apply_keyshares(&quorum_set, queries.iter().copied());
            let hashes = security_context
                .recombine(&responses, &keyshares.active_security_key)
                .unwrap();
            assert_eq!(hashes.len(), windows.len());
        }
    }

    #[test]
    fn padding_increases_size_of_response() {
        let windows = ["foo", "bar", "baz"];
        // Rather that testing against particular numbers of queries, which would heavily couple
        // this test to Verifier details, we check that padding increases the number of queries
        // by the specified amount.
        let paddings = [0, 1, 2, 3, 8, 25];
        let lens = paddings.map(|padding| {
            let (queries, _) = setup_queries(OsRng, windows, padding, SECURITY_PARAMETER);
            queries.len()
        });
        for (len, padding) in lens.into_iter().zip(paddings) {
            assert_eq!(len - lens[0], padding);
        }
    }

    #[test]
    fn queries_are_potentially_blinded() {
        let windows = ["foo", "bar", "baz"];
        let padding = 0;
        let (queries1, _) = setup_queries(OsRng, windows, padding, SECURITY_PARAMETER);
        let (queries2, _) = setup_queries(OsRng, windows, padding, SECURITY_PARAMETER);
        for (q1, q2) in queries1.iter().zip(queries2.iter()) {
            assert_ne!(q1.as_bytes(), q2.as_bytes());
        }
    }

    #[test]
    fn recombine_rejects_missing_responses() {
        let rng = &mut OsRng;
        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let keyshares = KeyShares::random(rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(rng);
        let padding = 0;
        let windows = [""];

        let (queries, security_context) =
            setup_queries(&mut *rng, windows, padding, SECURITY_PARAMETER);
        let mut responses = keyshares.apply_keyshares(&quorum_set, queries.iter().copied());
        let bad_response_i = rng.gen_range(0..responses.len());
        responses.swap_remove(bad_response_i);
        let err = security_context
            .recombine(&responses, &keyshares.active_security_key)
            .unwrap_err();
        assert!(matches!(err, QueryError::MissingKeyserverResponse));
    }

    #[test]
    fn recombine_rejects_too_short_responses() {
        let rng = &mut OsRng;
        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let keyshares = KeyShares::random(rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(rng);
        let padding = 0;
        let windows = [""];

        let (queries, security_context) =
            setup_queries(&mut *rng, windows, padding, SECURITY_PARAMETER);
        let mut responses = keyshares.apply_keyshares(&quorum_set, queries.iter().copied());
        let bad_response_i = rng.gen_range(0..responses.len());
        responses[bad_response_i].1.pop();
        let err = security_context
            .recombine(&responses, &keyshares.active_security_key)
            .unwrap_err();
        assert!(matches!(err, QueryError::WrongSizeResponse));
    }

    #[test]
    fn recombine_rejects_too_long_responses() {
        let rng = &mut OsRng;
        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let keyshares = KeyShares::random(rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(rng);
        let padding = 0;
        let windows = [""];

        let (queries, security_context) =
            setup_queries(&mut *rng, windows, padding, SECURITY_PARAMETER);
        let mut responses = keyshares.apply_keyshares(&quorum_set, queries.iter().copied());
        let bad_response_i = rng.gen_range(0..responses.len());
        let hash_part = HashPart::from_rp(RistrettoPoint::random(rng)).compress();
        responses[bad_response_i].1.push(hash_part);
        let err = security_context
            .recombine(&responses, &keyshares.active_security_key)
            .unwrap_err();
        assert!(matches!(err, QueryError::WrongSizeResponse));
    }

    #[test]
    fn recombine_rejects_invalid_ristrettos() {
        let rng = &mut OsRng;
        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let keyshares = KeyShares::random(rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(rng);
        let padding = 0;
        let windows = [""];

        let (queries, security_context) =
            setup_queries(&mut *rng, windows, padding, SECURITY_PARAMETER);
        let mut responses = keyshares.apply_keyshares(&quorum_set, queries.iter().copied());
        let bad_response_i = rng.gen_range(0..responses.len());
        let hashparts = &mut responses[bad_response_i].1;
        let bad_hashpart_i = rng.gen_range(0..hashparts.len());
        corrupt_hashpart(&mut hashparts[bad_hashpart_i]);
        let err = security_context
            .recombine(&responses, &keyshares.active_security_key)
            .unwrap_err();
        assert!(matches!(err, QueryError::InvalidRistrettoPoint(_)));
    }

    #[test]
    fn corrupted_keyservers_cause_query_error_and_are_correctly_identified() {
        let mut rng = OsRng;

        let num_required_keyshares = 2..6;
        let num_additional_keys = 0..6;
        let mut keyshares =
            KeyShares::random(&mut rng, num_required_keyshares, num_additional_keys);
        let quorum_set = keyshares.random_quorum_set(&mut rng);
        let corrupted_ks_set = random_populated_subset(&mut rng, &quorum_set);

        for ks_id in &corrupted_ks_set {
            *keyshares.share_mut(ks_id) = Scalar::random(&mut rng).into();
        }

        let windows = [
            "foobar",
            "The five boxing wizards jump quickly.",
            "",
            "acgtacgtacgt",
            "xyzzy",
        ];
        let padding = 0;

        let result =
            hash_via_keyshares(&mut rng, &keyshares, &quorum_set, padding, windows).unwrap_err();

        let expected_ks: Vec<_> = Vec::from(corrupted_ks_set);
        assert!(
            matches!(result, QueryError::ValidationFailed(ref responsible_ks)
                if responsible_ks == &expected_ks),
            "Should have found corrupted ks {expected_ks:?}, found {result:?}"
        );
    }

    quickcheck! {

        #[ignore]
        fn qc_distributed_keyshare_application_matches_single_key_application(
            rng: TestRng,
            keyshares: KeyShares,
            dna: Dna,
            padding: usize
        ) -> TestResult {
            if padding > 100 {
                return TestResult::discard();
            }
            let mut rng = rng;
            let dna: &[u8] = dna.0.as_ref();
            let windows = dna.windows(50);
            let quorum_set = keyshares.random_quorum_set(&mut rng);
            let padding = rng.gen_range(0..10);

            let output =
                hash_via_keyshares(rng, &keyshares, &quorum_set, padding, windows.clone()).unwrap();
            let expected = hash_via_key(&keyshares.secret, windows);

            TestResult::from_bool(output == expected)
        }

    }
}
