// Copyright 2021-2025 SecureDNA Stiftung (SecureDNA Foundation) <licensing@securedna.org>
// SPDX-License-Identifier: MIT OR Apache-2.0

use certificates::{
    bytes_from_pem,
    issuance_checks::{precheck_et_key, precheck_key, precheck_token_key},
    key::{ecies::EciesKeyPair, EncryptableKeypair},
    Attachment, AuditRecipient, Authenticator, Builder, CertificateBundle, Description, Domain,
    Exemption, ExemptionTokenGroup, ExemptionTokenRequest, Expiration, Manufacturer, Organism,
    PemDecodable, PemEncodable, PublicKey, RequestBuilder, Role, SigningKeyPair,
    SynthesizerTokenGroup, SynthesizerTokenRequest, SystemClock, TokenBundle, TokenGroup,
};
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// A custom bit of TypeScript code that integrates tsgen with wasm-bindgen.
///
/// The "all_bindings" referred to in this section is generated by
/// `wasm_bindings/build.rs`, which invokes tsgen and moves the bindings into
/// `wasm_bindings/*/pkg` where this snippet can see them.
#[wasm_bindgen(typescript_custom_section)]
const IMPORTS: &'static str = r#"
// Import/export bindings generated by `wasm_bindings/build.rs`:
import type {
    DataFromExistingSynthToken,
    EtrV1Fields,
    ExemptionToken,
    ExemptionTokenRequest,
    SignEtr,
} from "./all_bindings";
export * from "./all_bindings";
"#;

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct EtrV1Fields {
    public_key_pem: Option<String>,
    exemptions: Vec<Organism>,
    requestor: Description,
    requestor_auth_devices: Vec<Authenticator>,
    shipping_addresses: Vec<Vec<String>>,
    attachments: Vec<Attachment>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct SignEtr {
    etr_pem: Vec<u8>,
    cert_pem: Vec<u8>,
    private_key_pem: Vec<u8>,
    passphrase: Vec<u8>,
    validity_days: i64,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct CertRequestFiles {
    certr_pem: String,
    private_key_pem: String,
    public_key_pem: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct CreateSynthesizerToken {
    domain: String,
    model: String,
    serial: String,
    rate_limit: u64,
    audit_email: Option<String>,
    audit_passphrase: Option<String>,
    token_passphrase: String,
    cert_pem: String,
    cert_private_key_pem: String,
    cert_passphrase: String,
    days_valid: i64,
    existing_audit_pub_pem: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct DataFromExistingSynthToken {
    domain: String,
    model: String,
    serial: String,
    rate_limit: u64,
    audit_email: Option<String>,
    audit_public_key_pem: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct SynthesizerTokenFiles {
    private_key_pem: String,
    synthesizer_token_pem: String,
    new_audit_private_key_pem: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct PemKeyPair {
    private_key_pem: String,
    public_key_hexpem: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[wasm_bindgen(skip_typescript)]
// tsgen
pub struct CertInfo {
    all_emails_to_notify: Vec<String>,
}

// The block of code below lets us generate .d.ts files with proper TypeScript
// types. The types referred to are imported by `IMPORTS` above.
//
// We can't just e.g. use the Rust type `SignEtr` directly in the signatures in
// this file, as this generates a binding that expects an *instance* of some
// class `SignEtr`, whereas `SignEtr` is a plain JavaScript object.
//
// What the code below achieves is that `ISignEtr` is translated to `SignEtr`
// in the TypeScript bindings, but on the Rust side it's a "dummy" type that
// impls `Into<JsValue>`, on which we can use `serde_wasm_bindgen::from_value`.
//
// See also:
// * https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/typescript_type.html
// * https://github.com/rustwasm/wasm-bindgen/issues/2645
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "EtrV1Fields")]
    pub type IEtrV1Fields;
    #[wasm_bindgen(typescript_type = "ExemptionToken")]
    pub type IExemptionToken;
    #[wasm_bindgen(typescript_type = "ExemptionTokenRequest")]
    pub type IExemptionTokenRequest;
    #[wasm_bindgen(typescript_type = "SignEtr")]
    pub type ISignEtr;
    #[wasm_bindgen(typescript_type = "CertRequestFiles")]
    pub type ICertRequestFiles;
    #[wasm_bindgen(typescript_type = "CreateSynthesizerToken")]
    pub type ICreateSynthesizerToken;
    #[wasm_bindgen(typescript_type = "SynthesizerTokenFiles")]
    pub type ISynthesizerTokenFiles;
    #[wasm_bindgen(typescript_type = "PemKeyPair")]
    pub type IPemKeyPair;
    #[wasm_bindgen(typescript_type = "DataFromExistingSynthToken")]
    pub type IDataFromExistingSynthToken;
}

#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
    tracing_wasm::set_as_global_default();
}

#[wasm_bindgen]
pub fn make_etr_v1_pem(fields: IEtrV1Fields) -> Result<Vec<u8>, String> {
    let fields: EtrV1Fields = serde_wasm_bindgen::from_value(fields.into())
        .map_err(|e| format!("Couldn't decode JSON: {e:?}"))?;

    let mut requestor = fields.requestor;
    if requestor.phone_number.as_deref() == Some("") {
        requestor.phone_number = None;
    }
    if requestor.orcid.as_deref() == Some("") {
        requestor.orcid = None;
    }
    if requestor.name.as_deref() == Some("") {
        requestor.name = None;
    }
    let public_key: Option<PublicKey> = match fields.public_key_pem {
        Some(pem) => {
            Some(PublicKey::from_pem(pem).map_err(|_| "Couldn't decode public key".to_owned())?)
        }
        None => None,
    };

    let etr = ExemptionTokenRequest::v1_token_request(
        public_key,
        fields.exemptions,
        requestor,
        fields.requestor_auth_devices,
        fields.shipping_addresses,
        fields.attachments,
    );
    match etr.to_pem() {
        Ok(pem) => Ok(pem.into_bytes()),
        Err(e) => Err(format!("Couldn't encode PEM: {e:?}")),
    }
}

fn to_js<T: Serialize, U: From<JsValue>>(value: &T) -> Result<U, String> {
    match serde_wasm_bindgen::to_value(&value) {
        Ok(v) => Ok(v.into()),
        Err(e) => Err(format!("Couldn't convert to JS object: {e:?}")),
    }
}

fn etr_from_pem(etr_pem: Vec<u8>) -> Result<ExemptionTokenRequest, String> {
    ExemptionTokenRequest::from_pem(etr_pem)
        .map_err(|e| format!("Couldn't decode exemption token request: {e:?}"))
}

fn token_bundle_from_pem<T: TokenGroup>(
    et_pem: impl AsRef<[u8]>,
) -> Result<TokenBundle<T>, String> {
    TokenBundle::<T>::from_file_contents(et_pem)
        .map_err(|e| format!("Couldn't decode token bundle: {e:?}"))
}

fn cert_from_pem<R: Role>(cert_pem: impl AsRef<[u8]>) -> Result<CertificateBundle<R>, String> {
    CertificateBundle::from_file_contents(cert_pem)
        .map_err(|e| format!("Couldn't decode cert bundle: {e:?}"))
}

fn ecies_keypair_from_pem(
    ecies_pem: impl AsRef<[u8]>,
    ecies_passphrase: impl AsRef<[u8]>,
) -> Result<EciesKeyPair, String> {
    EciesKeyPair::load_key(ecies_pem, ecies_passphrase)
        .map_err(|e| format!("Couldn't load decryption key: {e:?}"))
}

fn load_key(
    priv_pem: impl AsRef<[u8]>,
    priv_passphrase: impl AsRef<[u8]>,
) -> Result<SigningKeyPair, String> {
    SigningKeyPair::load_key(priv_pem, priv_passphrase)
        .map_err(|_| "Couldn't decrypt key".to_string())
}

fn keypair_to_pem(
    keypair: SigningKeyPair,
    passphrase: impl AsRef<[u8]>,
) -> Result<PemKeyPair, String> {
    let public_key_hexpem = keypair
        .public_key()
        .to_file_contents()
        .map_err(|_| "Couldn't make public key PEM".to_owned())?;

    let mut private_key_pem: Vec<u8> = vec![];
    keypair
        .write_key(&mut private_key_pem, passphrase)
        .map_err(|_| "Couldn't encrypt private key".to_owned())?;

    let private_key_pem = String::from_utf8(private_key_pem)
        .map_err(|_| "Invalid UTF-8 in private key".to_owned())?;

    Ok(PemKeyPair {
        public_key_hexpem,
        private_key_pem,
    })
}

#[wasm_bindgen]
pub fn etr_pem_to_js_object(etr_pem: Vec<u8>) -> Result<IExemptionTokenRequest, String> {
    let etr = etr_from_pem(etr_pem)?;
    to_js(&etr)
}

#[wasm_bindgen]
pub fn et_bundle_pem_to_js_object(et_pem: Vec<u8>) -> Result<IExemptionToken, String> {
    let et_bundle = token_bundle_from_pem::<ExemptionTokenGroup>(et_pem)?;
    to_js(&et_bundle.token)
}

#[wasm_bindgen]
pub fn sign_etr(body: ISignEtr) -> Result<Vec<u8>, String> {
    let SignEtr {
        etr_pem,
        cert_pem,
        private_key_pem,
        passphrase,
        validity_days,
    } = serde_wasm_bindgen::from_value(body.into())
        .map_err(|e| format!("Couldn't decode JSON: {e:?}"))?;

    let etr = etr_from_pem(etr_pem)?;
    let keypair = load_key(private_key_pem, passphrase)?;
    let cert_bundle = cert_from_pem(cert_pem)?;

    let expiration = Expiration::expiring_in_days(validity_days)
        .map_err(|e| format!("Invalid expiration: {e:?}"))?;
    let et_bundle = cert_bundle
        .issue_exemption_token_bundle(etr, expiration, vec![], keypair)
        .map_err(|e| format!("Couldn't issue exemption token: {e:?}"))?;
    let et_pem = et_bundle
        .to_file_contents()
        .map_err(|e| format!("Couldn't encode exemption token: {e:?}"))?;

    Ok(et_pem.into_bytes())
}

#[wasm_bindgen]
pub fn create_manufacturer_leaf(
    name: String,
    email: String,
    passphrase: String,
) -> Result<ICertRequestFiles, String> {
    let keypair = SigningKeyPair::new_random();
    let desc = Description::default().with_name(name).with_email(email);
    let certr = RequestBuilder::<Manufacturer>::leaf_v1_builder(keypair.public_key())
        .with_description(desc)
        .build();
    let kp_pem = keypair_to_pem(keypair, passphrase)?;
    let files = CertRequestFiles {
        certr_pem: certr
            .to_pem()
            .map_err(|_| "Couldn't make certr pem".to_owned())?,
        private_key_pem: kp_pem.private_key_pem,
        public_key_pem: kp_pem.public_key_hexpem,
    };
    to_js(&files)
}

#[wasm_bindgen]
pub fn create_exemption_leaf(
    name: String,
    email: String,
    passphrase: String,
    totp_token_name: String,
) -> Result<ICertRequestFiles, String> {
    let keypair = SigningKeyPair::new_random();
    let desc = Description::default().with_name(name).with_email(email);
    let certr = RequestBuilder::<Exemption>::leaf_v1_builder(keypair.public_key())
        .with_description(desc)
        .with_totp_token_name(totp_token_name)
        .build();
    let kp_pem = keypair_to_pem(keypair, passphrase)?;
    let files = CertRequestFiles {
        certr_pem: certr
            .to_pem()
            .map_err(|_| "Couldn't make certr pem".to_owned())?,
        private_key_pem: kp_pem.private_key_pem,
        public_key_pem: kp_pem.public_key_hexpem,
    };
    to_js(&files)
}

#[wasm_bindgen]
pub fn create_synthesizer_token(
    body: ICreateSynthesizerToken,
) -> Result<ISynthesizerTokenFiles, String> {
    let CreateSynthesizerToken {
        domain,
        model,
        serial,
        rate_limit,
        audit_email,
        audit_passphrase,
        token_passphrase,
        cert_pem,
        cert_private_key_pem,
        cert_passphrase,
        days_valid,
        existing_audit_pub_pem,
    } = serde_wasm_bindgen::from_value(body.into())
        .map_err(|e| format!("Couldn't decode JSON: {e:?}"))?;

    let keypair = load_key(cert_private_key_pem, cert_passphrase)?;
    let cert_bundle = cert_from_pem(cert_pem)?;

    let mut new_audit_private_key_pem: Option<String> = None;

    let audit_recipient = match (audit_email, audit_passphrase, existing_audit_pub_pem) {
        (None, None, None) => Ok(None),
        (Some(email), Some(passphrase), None) => {
            let kp = EciesKeyPair::new_random();
            let mut priv_pem_bytes: Vec<u8> = vec![];
            kp.write_key(&mut priv_pem_bytes, passphrase)
                .map_err(|_| "Couldn't encrypt private key".to_owned())?;
            let priv_pem = String::from_utf8(priv_pem_bytes)
                .map_err(|_| "Invalid UTF-8 in private key".to_owned())?;
            new_audit_private_key_pem = Some(priv_pem);
            Ok(Some(AuditRecipient::new(email, kp.public_key())))
        }
        (Some(email), None, Some(existing_pub_pem)) => {
            let public_key = existing_pub_pem
                .parse()
                .map_err(|_| "Audit key parse error".to_owned())?;
            Ok(Some(AuditRecipient::new(email, public_key)))
        }
        (None, _, _) => Err("Missing audit email".to_owned()),
        (Some(_), None, None) => {
            Err("Missing audit public key or passphrase for new key".to_owned())
        }
        (Some(_), _, _) => {
            Err("Both audit public key and passphrase for new key were given".to_owned())
        }
    }?;

    let domain = Domain::try_new(domain).map_err(|e| e.to_string())?;

    let token_keypair = SigningKeyPair::new_random();
    let token_request = SynthesizerTokenRequest::v1_token_request(
        token_keypair.public_key(),
        domain,
        model,
        serial,
        rate_limit,
        audit_recipient,
    );
    let token_kp_pem = keypair_to_pem(token_keypair, token_passphrase)?;

    let expiration = Expiration::expiring_in_days(days_valid)
        .map_err(|e| format!("Invalid expiration: {e:?}"))?;

    let token_bundle = cert_bundle
        .issue_synthesizer_token_bundle(token_request, expiration, keypair)
        .map_err(|_| "Failed to issue token bundle".to_owned())?;

    let files = SynthesizerTokenFiles {
        private_key_pem: token_kp_pem.private_key_pem,
        synthesizer_token_pem: token_bundle
            .to_file_contents()
            .map_err(|_| "Couldn't make synth token pem".to_owned())?,
        new_audit_private_key_pem,
    };
    to_js(&files)
}

#[wasm_bindgen]
pub fn subset_et(
    et_pem: Vec<u8>,
    etr_pem: Vec<u8>,
    priv_pem: Vec<u8>,
    priv_passphrase: Vec<u8>,
    validity_days: u32,
) -> Result<Vec<u8>, String> {
    let et_bundle = token_bundle_from_pem::<ExemptionTokenGroup>(et_pem)?;
    let etr = etr_from_pem(etr_pem)?;
    let keypair = load_key(priv_pem, priv_passphrase)?;
    let expiration = Expiration::expiring_in_days(validity_days as i64)
        .map_err(|e| format!("Invalid expiration: {e:?}"))?;
    let sub_et = et_bundle
        .issue_exemption_token_bundle(
            etr,
            expiration,
            et_bundle.token.issuer_auth_devices().to_vec(),
            keypair,
        )
        .map_err(|e| format!("Failed to issue subset exemption token: {e:?}"))?;
    let sub_et_pem = sub_et
        .to_file_contents()
        .map_err(|e| format!("Couldn't encode exemption token: {e:?}"))?;

    Ok(sub_et_pem.into_bytes())
}

#[wasm_bindgen]
pub fn make_keypair(passphrase: String) -> Result<IPemKeyPair, String> {
    to_js(&keypair_to_pem(SigningKeyPair::new_random(), passphrase)?)
}

pub fn get_cert_info<R: Role>(cert_pem: String) -> Result<JsValue, String> {
    let cert_bundle = cert_from_pem::<R>(cert_pem)?;
    let cert = cert_bundle
        .get_lead_cert(&SystemClock)
        .map_err(|e| format!("Failed to get lead cert: {e}"))?;
    let cert_info = CertInfo {
        all_emails_to_notify: cert.all_emails_to_notify(),
    };
    to_js(&cert_info)
}

pub fn check_cert<R: Role>(
    cert_pem: String,
    priv_pem: String,
    priv_passphrase: String,
) -> Result<JsValue, String> {
    let cert_bundle = cert_from_pem::<R>(cert_pem)?;
    let result = precheck_key::<R>(&cert_bundle, &priv_pem, &priv_passphrase, &SystemClock);
    to_js(&result)
}

#[wasm_bindgen]
pub fn check_manufacturer_cert(
    cert_pem: String,
    priv_pem: String,
    priv_passphrase: String,
) -> Result<JsValue, String> {
    check_cert::<Manufacturer>(cert_pem, priv_pem, priv_passphrase)
}

#[wasm_bindgen]
pub fn check_exemption_cert(
    cert_pem: String,
    priv_pem: String,
    priv_passphrase: String,
) -> Result<JsValue, String> {
    check_cert::<Exemption>(cert_pem, priv_pem, priv_passphrase)
}

#[wasm_bindgen]
pub fn check_synth_token(
    st_pem: String,
    priv_pem: String,
    priv_passphrase: String,
) -> Result<JsValue, String> {
    let st = token_bundle_from_pem::<SynthesizerTokenGroup>(st_pem)?;
    let result = precheck_token_key::<_, Manufacturer>(st, &priv_pem, &priv_passphrase);
    to_js(&result)
}

#[wasm_bindgen]
pub fn check_exemption_token(
    et_pem: String,
    priv_pem: String,
    priv_passphrase: String,
) -> Result<JsValue, String> {
    let et = token_bundle_from_pem::<ExemptionTokenGroup>(et_pem)?;
    let result = precheck_et_key(et, &priv_pem, &priv_passphrase);
    to_js(&result)
}

#[wasm_bindgen]
pub fn check_ecies_private_key(
    esr_pem: String,
    ecies_pem: String,
    ecies_passphrase: String,
) -> Result<JsValue, String> {
    let _ = decrypt_encrypted_screening_response(esr_pem, ecies_pem, ecies_passphrase)?;
    to_js(&())
}

/// The result of this function is a list of bytes, which *should* be valid
/// JSON, but to keep this wrapper light and flexible, we'll leave the
/// JSON-parsing work for the web interface to do.
#[wasm_bindgen]
pub fn decrypt_encrypted_screening_response(
    esr_pem: String,
    ecies_pem: String,
    ecies_passphrase: String,
) -> Result<Vec<u8>, String> {
    let kp = ecies_keypair_from_pem(ecies_pem, ecies_passphrase)?;
    let encrypted = bytes_from_pem(
        &esr_pem,
        "SECUREDNA ENCRYPTED SCREENING RESPONSE".to_owned(),
    )
    .map_err(|_| "Not a valid encrypted screening response".to_owned())?;
    kp.decrypt(encrypted).map_err(|_| {
        "Failed to decrypt screening response. (Are you using the right keypair?)".to_owned()
    })
}

#[wasm_bindgen]
pub fn extract_data_from_existing_synth_token(
    synth_token_pem: String,
) -> Result<IDataFromExistingSynthToken, String> {
    let st = token_bundle_from_pem::<SynthesizerTokenGroup>(synth_token_pem)?;

    let data = DataFromExistingSynthToken {
        domain: st.token.manufacturer_domain().to_owned(),
        model: st.token.model().to_owned(),
        serial: st.token.serial_number().to_owned(),
        rate_limit: st.token.max_dna_base_pairs_per_day(),
        audit_email: st.token.audit_email().map(|a| a.to_string()),
        audit_public_key_pem: st.token.audit_email_public_key().map(|a| a.to_string()),
    };

    to_js(&data)
}
