[package]
name = "system_tests"
version = { workspace = true }
publish = { workspace = true }
license = { workspace = true }
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
run_system_tests = []

[dependencies]
anyhow = "1.0.75"
hex = "0.4"
reqwest = { version = "0.12.7", features = ["blocking", "json", "rustls-tls"] }
serde_json = "1"
sha3 = "0.10.8"
tokio = { version = "1", features = ["full"] }

certificates = { path = "../certificates" }
hdb_api = { path = "../hdb_api" }
pipeline_bridge = { path = "../pipeline_bridge" }
shared_types = { path = "../shared_types" }
synthclient = { path = "../synthclient" }
